### PR TITLE
Change prompt message to a more meaningful one

### PR DESCRIPTION
**Pull request by brenoc**
Change login prompt messages from this:
```
> account
> email
> password (typing will be hidden)
```
To:

```
> account name of the store you are developing
> email
> password (typing will be hidden)
```

### CODE REVIEW

**Comment by tamorim** [comment]
I disagree with such a huge name, I prefer to inform what an account is via the docs, or find a 2 word name to be prompted.

**Comment by dfosco** [comment]
I was confused with this detail the first time I ran the new toolbelt, and I'm sure many developers will overlook this detail in their _first interaction using it_.

Are you sure a small explanation isn't worth it? Just to save the quick trip to the docs. What about:

```
> account (name of the store you are developing)
> email
> password (typing will be hidden)
```

**Comment by brenoc** [comment]
I agree with @dfosco.

I think is more intuitive and less error prone. Docs may say how it's done right, but won't make it more intuitive to use.

The dream of any UX is *"no docs needed"*

**Comment by tamorim** [comment]
I didn't said that I don't agree, I think that it's a little confusing, indeed.
I just think that the message shouldn't as long, it should be something subtle.
That's why I said that something with 2 words is ideal.

**Comment by tamorim** [comment]
`store account`?

**Comment by dfosco** [comment]
@tamorim If the goal is clarity, I see no reason why we should keep to two words — `store account` is somewhat self-explanatory, but not the most intuitive way to phrase it.

**Comment by tamorim** [comment]
Well, let me illustrate why I don't like it:

(actually it shows `login`, not `email`)
```
> account name of the store you are developing
> login
> password (typing will be hidden)
```

- I don't think a **terminal prompt** is a place for that
- What about email and password? Some people might get confused to what it means too
- It's a big arrow saying "Hey. we couldn't find a nice word to describe what we want, so we put his thing instead"

Maybe it's a better approach to do something like:

```
$ vtex login
account - The store account you want to be developing on
login - Your VTEX registered e-mail
password - Your VTEX registered password

> account
> login
> password (typing will be hidden)
```

I don't think it's perfect, but it's better because doesn't get in the way of the prompt and explains all prompts at once, so the user will understand everything he has to type beforehand.

What do you guys think?

**Comment by dfosco** [comment]
@tamorim That seems like an ideal setup for me. Will the descriptions appear every time the user wants to login?

**Comment by tamorim** [comment]
@dfosco Yes.

**Comment by dfosco** [comment]
@tamorim We have a winner!!! :checkered_flag:

**Comment by brenoc** [comment]
:+1:

**Comment by tamorim** [comment]
@brenoc @dfosco Updated!

**Pull request merged**
