### PR TITLE
Refactor and restructure for V1

### PR DESCRIPTION
**Pull request by firstdoit**
From https://github.com/vtex/toolbelt/issues/137

### CODE REVIEW

**Comment by firstdoit** [comment]
@rdumont your wish is my command 🙇 

image

**Comment by firstdoit** [comment]
@rdumont also fixed `create` and `user agent`

**Comment by brenoc** [comment]
What do you think changing "Buckets" do "Services"?

**Comment by brenoc** [comment]
That's look great!

**Comment by rdumont** [comment]
@firstdoit, the "Buckets" column should only list buckets that have changes, in order to know what the workspace is all about.

**Comment by firstdoit** [comment]
@rdumont indeed, indeed! Here you go:

image

**Comment by firstdoit** [comment]
🎉

**Pull request merged**
