### PR TITLE
Use request wrapper with retry capability

### PR DESCRIPTION
**Pull request by firstdoit**
Fixes https://github.com/vtex/toolbelt/issues/90

@tamorim can you take this branch for a spin?

From https://github.com/FGRibreau/node-request-retry

> When the connection fails with one of ECONNRESET, ENOTFOUND, ESOCKETTIMEDOUT, ETIMEDOUT, ECONNREFUSED, EHOSTUNREACH, EPIPE, EAI_AGAIN or when an HTTP 5xx error occurrs, the request will automatically be re-attempted as these are often recoverable errors and will go away on retry.

```
  // The below parameters are specific to request-retry
  maxAttempts: 5,   // (default) try 5 times
  retryDelay: 5000,  // (default) wait for 5s before trying again
```

### CODE REVIEW

**Comment by firstdoit** [comment]
Hmm apparently this "drop-in" is not that "drop-in".

```
Watching pilateslovers-theme

/Users/guilherme/Projects/VTEX/toolbelt/node_modules/q/q.js:155
                throw e;
                ^

Error: A callback was provided but waiting a promise, use only one pattern
    at Request.exposedPromiseMethod [as then] (/Users/guilherme/Projects/VTEX/toolbelt/node_modules/requestretry/index.js:129:13)
    at /Users/guilherme/Projects/VTEX/toolbelt/node_modules/q/q.js:1184:21
    at runSingle (/Users/guilherme/Projects/VTEX/toolbelt/node_modules/q/q.js:137:13)
    at flush (/Users/guilherme/Projects/VTEX/toolbelt/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by firstdoit** [comment]
Fixed 👍

**Comment by brenoc** [comment]
What it does? @firstdoit

**Comment by firstdoit** [comment]
Sorry @brenoc, updated the original PR!

**Comment by brenoc** [comment]
LGTM :+1: 

@tamorim you're the owner, your call

**Comment by tamorim** [comment]
:+1:

**Pull request merged**
