### PR TITLE
Change codebase to ES6

### PR DESCRIPTION
**Pull request by brenoc**
Moving on!

### CODE REVIEW

**Comment by tamorim** [comment]
@brenoc Waiting for stable approval! :D
Just say the word! It's beautiful!!!

**Comment by brenoc** [comment]
@tamorim You can merge it next week, after the turmoil of the Great Break™

**Comment by tamorim** [comment]
@brenoc
BEHOLD
DA
MERRGE!!
:fire: fire: fire:

**Comment by tamorim** [comment]
@brenoc Could you please write the CHANGELOG for this version? :)
I think it will be more appropriate!
Remeber to put on the `CHANGELOG` and on the tag too! :smiley:

**Comment by brenoc** [comment]
@tamorim sure!

**Comment by brenoc** [comment]
Will be an honor!

**Pull request merged**
