### PR TITLE
enables vtex components to work on render8

### PR DESCRIPTION
**Pull request by juaresba**
#### What is the purpose of this pull request?
This pull request applies changes so that for VTEX Components (https://github.com/vtex-components), the root package.json can be uploaded and linked. It also adds a step when uploading files to adapt this package.json, more specifically when the vtexComponentsEnabled property on the manifest.json is set to true.

#### What problem is this solving?
This pull request enables VTEX Components  to work in the render 8.

#### How should this be manually tested?
Installing this version of the CLI used to install the vtex template, running `vtex link` and checking if the template is working properly on render 8.

#### Types of changes
- [ ] Refactor (non-breaking change that only makes the code better)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

#### Chores checklist
- [ ] Update `CHANGELOG.md`

### CODE REVIEW

**Comment by emersonlaurentino** [comment]
this pr it will be merged when https://github.com/vtex/builder-hub/pull/1053 was merged

**Comment by gris** [comment]
Hey @juaresba is this still valid? SHould we work towards merging it?

**Comment by juaresba** [comment]
Hello, @gris. I think @emersonlaurentino knows better if it makes sense to work towards merging it, I have not been working directly with the SFJ in the past few months. It should still work. If you have any doubt about how it works reach me out on slack.

**Comment by gris** [comment]
Nice! I'm just trying to make sure that we're not missing any PRs that need our attention. I will wait for @emersonlaurentino 
inputs in that case.

**Pull request closed without merging**
